### ISSUE TITLE
msg.payload always true and msg.AllBinary data always 11111111 (255d)

### ISSUE THREAD

**Issue by HarterHorst** [PizzaProgram/MCP23017-PCF8574-AIO#3]
**System Config:**

```
Mar 27 10:36:07 raspberrypi Node-RED[16051]: Welcome to Node-RED
Mar 27 10:36:07 raspberrypi Node-RED[16051]: ===================
Mar 27 10:36:07 raspberrypi Node-RED[16051]: 27 Mar 10:36:07 - [info] Node-RED version: v2.2.2
Mar 27 10:36:07 raspberrypi Node-RED[16051]: 27 Mar 10:36:07 - [info] Node.js  version: v14.19.1
Mar 27 10:36:07 raspberrypi Node-RED[16051]: 27 Mar 10:36:07 - [info] Linux 5.10.103-v7l+ arm LE
Mar 27 10:36:08 raspberrypi Node-RED[16051]: 27 Mar 10:36:08 - [info] Loading palette nodes
Mar 27 10:36:10 raspberrypi Node-RED[16051]: 27 Mar 10:36:10 - [info] Settings file  : /home/pi/.node-red/settings.js
Mar 27 10:36:10 raspberrypi Node-RED[16051]: 27 Mar 10:36:10 - [info] Context store  : 'default' [module=memory]
Mar 27 10:36:10 raspberrypi Node-RED[16051]: 27 Mar 10:36:10 - [info] User directory : /home/pi/.node-red
Mar 27 10:36:10 raspberrypi Node-RED[16051]: 27 Mar 10:36:10 - [warn] Projects disabled : editorTheme.projects.enabled=false
Mar 27 10:36:10 raspberrypi Node-RED[16051]: 27 Mar 10:36:10 - [info] Flows file     : /home/pi/.node-red/flows.json
Mar 27 10:36:10 raspberrypi Node-RED[16051]: 27 Mar 10:36:10 - [info] Server now running at http://127.0.0.1:1880/
Mar 27 10:36:10 raspberrypi Node-RED[16051]: 27 Mar 10:36:10 - [warn]
Mar 27 10:36:10 raspberrypi Node-RED[16051]: 27 Mar 10:36:10 - [info] Starting flows
Mar 27 10:36:10 raspberrypi Node-RED[16051]:   MCP/FCP context does not exists yet. Creating now: i2c1RW
Mar 27 10:36:10 raspberrypi Node-RED[16051]:   MCP/PCF chip initialization OK. BusNumber=1 Address=126  id:d404151b1e63dc2b
Mar 27 10:36:10 raspberrypi Node-RED[16051]: ---
Mar 27 10:36:10 raspberrypi Node-RED[16051]: >>> Initializing PCF8574 or MPC23017 Input node >>  bitNum=0  pullUp=false  invert=false  id=f3e9efa753c41827
Mar 27 10:36:10 raspberrypi Node-RED[16051]:   MCP/PCF init-Bit started... Addr=126  bitNum=0  isInput=true  pullUp=false  startAllHigh=false  LastState=-2
Mar 27 10:36:10 raspberrypi Node-RED[16051]: OK. MCP/PCF Bit-initialization finished. Bus closed.
Mar 27 10:36:10 raspberrypi Node-RED[16051]:   ...state update >>  _onOffState: 1   globalState= 1  Node_id=f3e9efa753c41827
Mar 27 10:36:10 raspberrypi Node-RED[16051]:   MCP/PCF startChipTimer = 00 ms
Mar 27 10:36:10 raspberrypi Node-RED[16051]:   MCP/PCF  Timer interval is UNDEFINED or 0 ! Timer will not be started. Exiting.
```
**NodeRed Flow:**

```
[{"id":"5c330a635140c82d","type":"tab","label":"Flow 2","disabled":false,"info":"","env":[]},{"id":"9e21d99bdab7b3e7","type":"debug","z":"5c330a635140c82d","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":510,"y":280,"wires":[]},{"id":"b7fa6f0c7ba76672","type":"rpi-gpio in","z":"5c330a635140c82d","name":"Check GPIO17","pin":"17","intype":"up","debounce":"25","read":false,"bcm":true,"x":120,"y":240,"wires":[["f3e9efa753c41827"]]},{"id":"f3e9efa753c41827","type":"MCP PCF In","z":"5c330a635140c82d","name":"PCF8574A","chip":"d404151b1e63dc2b","bitNum":"0","invert":false,"pullUp":false,"debounce":"240","onMsg":true,"offMsg":true,"x":350,"y":280,"wires":[["9e21d99bdab7b3e7"]]},{"id":"2f7586a95a3fa956","type":"inject","z":"5c330a635140c82d","name":"Send 1","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"1","payloadType":"num","x":130,"y":300,"wires":[["f3e9efa753c41827"]]},{"id":"d404151b1e63dc2b","type":"mcp_pcf_chip","busNum":"1","addr":"0x7E","interval":"0","startAllHIGH":false}]
```

**Expected behaviour:**

- msg.AllBinary reflects the PIN Status of the PCF8574
- msg.payload reflects the PIN status of the specific PIN configured in PCF8574 Node under Bit Number (0-15).

**Behaviour:**

- msg.AllBinary is always 11111111. Even if flow is triggered by inject node simulating an interrupt.
- msg.payload ist always true regardless of interrupt via GPIO Pin or triggered by inject node.

**Test Flow:**

First debug output: PCF8574 generated an interrupt due to PIN0 going high. GPIO Node detects that and sends out "1" to PCF8574 Node which checks the PIN status. 
Second debug output: Just pressed the inject node to simulate interrupt. 
 
<img width="1041" alt="Screenshot 2022-03-27 at 11 35 07" src="https://user-images.githubusercontent.com/22732869/160275903-84b22d3c-b520-45f7-b2d4-e951b69d233a.png">

**Comment by PizzaProgram** [comment]
Thank you very much for your detailed report.

1. PCF8574 has only 8 pins. So it's not 0-15 but 0-7 only.
2. The 11111111 is the "normal" state of the chip. Only if you give GND to one of the pin, it will be "closed" to 0.
3. You may use 8 nodes and set all of them to "invert", but direct triggered input will not be effected by it. Raw and Binary read will show the chip's direct values.
4. There was a bad version 3 uploads ago reporting always true to all pins. Fixed 7 days ago. See: version 2.3.1.20220321
5. **So did You upgrade to the latest version? 2.3.5.xx ?**
6. Did You restart node-red after upgrade, and reloaded the webpage?
7. If an other pin is changed when you force a "direct-read", the Node's visual On/Off will obviously not change and it will not trigger any OnMsg or OffMsg event.

Yes, it is still possible I've left an error somewhere, because debugging is not working under VSCode + Raspberry Pi for me. This is my first JavaScript code and I'm programming it "blindly". (Logs only, no step-by-step debug.)

PS:
I've just realised I have used big start letters, not lowercase: `allStatesRaw` , `allBinary`. Should I change them now?

![kép](https://user-images.githubusercontent.com/26026089/160279632-4f0cffe1-54e6-41fe-b878-fc3eaadbded3.png)

**Comment by HarterHorst** [comment]
Hi, thanks for the comprehensive answer. I think I got it now.

- The interrupt PIN from the PCF8574 has to be connected to the Raspberry PINs using a pull-up resistor to bring the pin high on default. When an event occurs on the I/O Pins of the chip, the interrupt is set to low / ground to tell the raspi something has happened.
- In my flow I catch the interrupt with nodered standard Raspberry GPIO Pin node, which throws events in case of changes on the PIN. In my specific case the first event is thrown when the button is pressed (PIN low / GND) with payload 0 and the second when the button is released (PIN getting back to high because of pull-up Resistors / VCC) with payload 1. 
- In order to get the values from the register your node requires a 1 (true) on the input side. In my case this is done when the PCF8574 Pin is back to normal. 
- So the register call is made at a time when the button has been released and therefore the result is always 255.

I changed the input to accept only 0 / false msg.payload to get the register and now it works. 

I don't know the recommendations for other chips, but if pull-up of the interrupt line is recommended on other chips as well it might be better to trigger your node with 0/false.

Regarding remote debugging of nodered with VSC. It's quite tricky but I figured it out. My workaround is to start nodered on the raspi from the command line with the required parameter and then connect to the running process from my MacBook with VSC. You should give it a try. Of course you have to check the path parameters. Triggering the start of nodered in debug mode remotely  never worked. The VSC Session never connected to the debugger. 
```
node --nolazy --inspect-brk=9229 /usr/lib/node_modules/node-red/red.js -v --userDir /home/pi/.node-red -s /home/pi/.node-red/settings.js
```
Then select debug: Attach to node process in VSC and your on. Short hint: If you have multiple entries in the list check the process ID on the raspberry with ps -xf and you know which entry to select in VSC.

**Comment by PizzaProgram** [comment]
Wow!
 Thank you very much for the detailed explanation and the testing!

- I'll test that debugging possibility in a few days.
- I guess it's better if I just make a hint or example about "false" as trigger. Did you change the code itself, or simply put a "change" node before it to invert?
- I'm planning to connect the int pin to my RPi too, so you have saved me lot's of time. :-)
- How strong resistor did you use?  
- Did You simply connected: [Rpi pin] -- [resistor] -- [chip int pin] ?
- How long is you I2C wire?

I have spent several weeks to find a solution for debugging, but did not success. If this is going to work, I'll go crazy happy about it. I'll test it in a few days. Currently I have to work.

**Comment by PizzaProgram** [comment]
# Debugging is WORKING :+1: 

1. Copied this to `package.json` : 
```json
  "scripts": {
    "node-red": "node --nolazy --inspect-brk=9229 /usr/lib/node_modules/node-red/red.js -v --userDir /home/pi/.node-red -s /home/pi/.node-red/settings.js"
  },
```
2.
If you hover your mouse over the "script" line > you can choose "run script with debugging" ... or similar (translated)

3.
 Than I've created a new entry in `launch.json` : 
```json
    "version": "0.2.0",
    "configurations": [
        {
            "address": "127.0.0.1",
            "localRoot": "${workspaceFolder}",
            "name": "Attach to Remote NR",
            "port": 9229,
            "remoteRoot": "/home/pi/MCP23017-PCF8574-AIO",
            "request": "attach",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "type": "pwa-node"
        },
```

4. Saved it
5. Chosed from the dropdown list next to the green triangle the "Attach to Remote NR"
6. Clicked "play" = green arrow.


The only problem is currently, that the debugging consol is overfilled with Temp and CPU reading:
![kép](https://user-images.githubusercontent.com/26026089/160451430-fbf489d1-9f3b-4def-b63d-636073ef0139.png)
