### ISSUE TITLE
Node red crashes

### ISSUE THREAD

**Issue by geoffreydemaagd** [PizzaProgram/MCP23017-PCF8574-AIO#4]
Thanks for the great node!

But sometimes node red crashes on de mainChipNode.warning with no particular reason

[red] Uncaught Exception:
[error] TypeError: mainChipNode.warning is not a function
at Timeout.myTimer [as _onTimeout] (/home/pi/.node-red/node_modules/@pizzaprogram/mcp-pcf-aio/mcp-pcf-aio.
at listOnTimeout (internal/timers.js:557:17)
at processTimers (internal/timers.js:500:7)
 Main process exited, code=exited, status=1/FAILURE

Shouldn't it be .warn instead of .warning?

**Comment by PizzaProgram** [comment]
Thanks for reporting it, I'll investigate.
What version of NodeRed are you using?

**Comment by PizzaProgram** [comment]
New version available: 2.3.6-20220606
Please test it. ;-)
