### ISSUE TITLE
Reading MCP23017 after interrupt is not working many times

### ISSUE THREAD

**Issue by geoffreydemaagd** [PizzaProgram/MCP23017-PCF8574-AIO#5]
First many thanks for this great node. I was waiting for years and you managed to do it. Thumbs up!

But now I have a problem.
I don't know what's causing this behaviour but interrupts do not work smoothly.

I use this node for my pushbuttons  all over my house which are linked to the GPIO plus MCP23017.

Apparently when pushing the buttons for a shorter period than for example 2 seconds the interrupt is always seen by the RPI and I trigger the 'force read of your node. But nothing is found in the MCP23017 to be updated.

I have already played with debounce, read timings etc but now I quite desperate.

Do you have any idea/clue how this can be fixed? Is it a problem with I2C?

**Comment by PizzaProgram** [comment]
What value did you set for read frequency = repeated read ? (ms)

Did you read about interrupt here? 
https://github.com/PizzaProgram/MCP23017-PCF8574-AIO/issues/3#issuecomment-1080815256

**Comment by PizzaProgram** [comment]
I admit. I have not tested with interrupts yet.
Theoretically MPC chip should report both push and release, but only if the chip is set in that way.

As alternative, you may start a repeated forced-read for 1-2 sec long after first interrupt arrived.
In that way if will not spin the CPU for long time, if nobody is pushing anything.

If you don't know how to create / stop timers+intervals in Node-RED, ask at their forum, they are very helpful!

**Comment by geoffreydemaagd** [comment]
When the MCP23017 found a bit that needs to be updated I get 4 msg on the RPI input interrupt ( 0 1 0 1)
When the chips doesn't see any bit that needs to be updated, i get 0 - 1 only
What is logic cause the program clears the interrupt when a bit has been changed.

I my case the 0 triggers a force read input.

Already tried with reading time 50, 100 350 ms, 500ms, even 10000 seconds. This doesn't change anything on the missing bit change.

It's like something is clearing the changed bit without transmitting that an event occured.

**Comment by PizzaProgram** [comment]
Sorry for the late response, I've looked 2x into the code + analysed again the original PDF of the chip.
_Here is where I am now with my investigation:_  

1. IOCON is setting general interrupt method: _(copied from PDF)_  
```
bit 2  ODR: Configures the INT pin as an open-drain output
  1 = Open-drain output (overrides the INTPOL bit.)
  0 = Active driver output (INTPOL bit sets the polarity.)
bit 1  INTPOL: This bit sets the polarity of the INT output pin
  1 = Active-high
  0 = Active-low
```
2. So it seems the default state is `0 = Active-low` and not BOTH on/off triggers interrupt.  
3. I have CHANGED the code to `ODR bit=1` . _Let's hope it will trigger both now._ New version will be online soon. (v2.3.8.20220907)  
4. Also, from now on:  
 `MIRROR bit=1` << If **any** of A or B input IO-bank pin changed, **both** INTA and INTB is triggered >> readAll will read all changes anyway. So it will be enough to wire only 1 interrupt to watch 16 pins.

Please test it, and report back!

**Comment by geoffreydemaagd** [comment]
I've tested it with 2.3.8-20220907

Now nothing arrives at the interrupt pin - the pin stays low all the time even when an event occured.

Before the pin was standaard high and went to low when an event occured.

**Comment by PizzaProgram** [comment]
Yesterday I'm analysed thoroughly the chip's PDF again + also some Adafruit/Arduino C code.
Found out, I have to activate one more thing (INTerrupt CONtrol) on all pins, to make BOTH changes (low/high) trigger a new interrupt:
`INTCON = 1111111111111111;`

The fix is available here on github, but not at NPM yet. So if you:
1. Download the .js file from here
2. Copy to .node-red's module directory, overwriting the old one
3. CMD to that directory and type `npm rebuild`
4. restart node-red 

You should be good to go.

Currently my test system is not working for some reason I can not find, so I'm too much afraid to release this new version to `npm` without testing.

**Comment by geoffreydemaagd** [comment]
I retrieved the file from https://github.com/PizzaProgram/MCP23017-PCF8574-AIO/blob/e486269053addfa24ba25eca0e41234515fe0c05/mcp-pcf-aio.js and updated to file, NPM rebuild en restarted NR.

Still there is nothing coming to the interrupt pins.

What I also find a strange behaviour that is when increasing the read interval, more and more events aren't transmitted to the IO pins. Can you explain me how the timer works? Is it possible when increasing the read internal, many changes on the pin aren't seen by the MCP23017. Or by introducing a timer instead of full interrupt working does trigger dis behaviour?

Even without th inrterrupt some push are seen by the code


!Change! of an i2c  MCP/PCF input. IP MASK0000=10000  Diff Mask0000=10000
  MCP/PCF  > ..searching for node i=4   id=fc400cd9febcabed  found node:[object Object]  glob_inp=65535
  MCP/PCF  > Found a Node needs to be updated. Bit=4 newState=true   LastState=0
  MCP/PCF > New input Debounce timer set.  TimeEnd=5  State=true
!Change! of an i2c  MCP/PCF input. IP MASK0000=0  Diff Mask0000=10000
  MCP/PCF  > ..searching for node i=4   id=fc400cd9febcabed  found node:[object Object]  glob_inp=65535
  MCP/PCF  > Found a Node needs to be updated. Bit=4 newState=false   LastState=0
  MCP/PCF > Input timer Bounce Ended. [NewState=0]   [Last State=0]  [Deb.state=false]  [Bit=4]  Ellapsed=NaNms

But nothing is tranmitted.

EDIT: i see i have to set de debounce to zero to pass all the events, will test this also
===>
Tested it, i'ts better but still missing some fast clicks. Maybe when the interrupts are working fine, the timer can be disabled? Cause when decreasing the ms interval read, the node complains at a certain moment that the interval is too small

Many thanks

**Comment by PizzaProgram** [comment]
> Still there is nothing coming to the interrupt pins.

That would be strange... I don't know anything else, why it would happen. 
**Can you share a picture + a Node-red export** of that area (MCP chip + RPi input + msg node)

- Did you put an extra [msg] node to the interrupt part (of the RPi) to watch it?

> Maybe when the interrupts are working fine, the timer can be disabled?

Yes, If you are using interrupts, theoretically you don't need intervals any more. 
But maybe 1x-2x pro sec = 500-1000ms should stay, to make sure the push button is at the "right state". 
_(So if anything bad happens, you don't have to wait 3 days, until someone is pushing that button again, with the "right speed".)_

> EDIT: i see i have to set de debounce to zero to pass all the events

Debounce should act as "read once more after trigger", but it complicates things. 
I think 25-50ms should be optimal, if enabled, but rather not.

Theoretically it should eliminate unstable readings (like sparks), but it is better to use resistors or even better some [optocouplers](https://duckduckgo.com/?q=optocoupler+12v+to+5v+price&t=ffab&ia=web) to make a stable ON / OFF wiring. (12Volt in the walls.)

> Cause when decreasing the ms interval read, the node complains at a certain moment that the interval is too small 

Yes, reading the state takes some time. (A few ms.) I've coded a fail-safe mechanism, so nobody can set an interval under the minimum. Also, if the last read took longer than expected, it will expand this time. 
This can happen if:
- the RPI is busy 
- or the I2C bus freq. is set to 10k instead of 100.000 baud/sec

**Comment by PizzaProgram** [comment]
- Is my node getting triggered by 0 not by 1 from RPi? 
 - Did you put a "change node" between ?
 - Is there a resistor between RPi's pin + MCP Chip's INTA port?
 - Did you wire both INTA + INTB to the RPi? (Not needed any more, because they are mirrored with this new version now)

**Comment by geoffreydemaagd** [comment]
Nothing arrives on the RPI input pin - so I think the interrupt of the mcp23017 is not working.
I've put a debug directly on the RPI pin thus the change is not the cause of it. I can share a picure of an input RPI pin connected to a debug node but maybe that's silly :-)

I've tried with and without the internal resistor (pullup and pulldown) of the rpi. 

Both interrupts are wired to the RPI to test (not necessary but just for test purposes)

ps I use optocouplers for the interrupt input to manage the 5v from my MCP23017 to a 3.3voltage

I 'm still confusing why an increase of the reading time increases the missings of push events.
Isn't the mcp23017 still holding the event till it is read by the node?

ps tested it with read interval 5000ùs and NOTHING arrives anymore. I think when resolving the problem in the timer and missing reads the mani issue (exept interrupts) will be gone.

**Comment by PizzaProgram** [comment]
> Nothing arrives on the RPI input pin - so I think the interrupt of the mcp23017 is not working.

Did it half-work before recent changes?
- if yes, you may change the code at Line 308 (second writeByteSync) from :
`aBus.writeByteSync(_parCh.addr, BNK1_IOCON_A	, 0xE4);`

to this:
`aBus.writeByteSync(_parCh.addr, BNK1_IOCON_A	, 0xE2);` // INTPOLarity=1
or this:
`aBus.writeByteSync(_parCh.addr, BNK1_IOCON_A	, 0xE0);` // INTPOLarity=0

...save it + rebuild NPM + restart node-red.

## You may also insert a new line there like:
`console.log('-------new version: 2022-09-09 ----------');`
or uncomment the // bbb(); lines:
`bbb();`
... to see, if you have succeeded to rebuild it and is it running.

**Comment by PizzaProgram** [comment]
```
//bit7 BANK	= 	1 : sequential register addresses (See PDF: Table 3-3)
//bit6 MIRROR	= 	1 : use configure Interrupt 
//bit5 SEQOP   	= 	1 : sequential operation disabled, address pointer does not increment
//bit4 DISSLW 	= 	0 : The "Slew Rate" bit controls the slew rate function on the SDA pin. If enabled, the SDA slew rate will be controlled when driving from a high to low.
//bit3 HAEN	= 	0 : hardware address pin is always enabled on 23017
//bit2 ODR	= 	0 : open drain output.  Enables/disables the INT pin for open-drain configuration. Setting this bit overrides the INTPOL bit.
//bit1 INTPOL  	= 	1 : interrupt active low (Sets the polarity of the INT pin. This bit is functional only when the ODR bit is cleared, configuring the INT pin as active push-pull)
//bit0 xxx unused  = 0 
    //       for example SEQOP = 1:   write ( addr, IOCON, 0b00100000 ); = 32 dec = 0x20
```

**Comment by geoffreydemaagd** [comment]
> 



>

**Comment by geoffreydemaagd** [comment]
Restoring the aBus.writeByteSync(_parCh.addr, BNK1_IOCON_A , 0xE4); to 0XE2 enables the interrupt again. Tested it.

But still I wanted he interrupt to work cause then I could decrease the timer. But uinfortunatly then nothing is found on the chip.
When the read timer is for ex. 100ms it works for 90%, 10% of the clicks aren't passed (even the interrupt not)
when the read timer is 5000ms nothing in passed, no event and no interrupt

Is it possible to look at the timer? It's like when in 'timer-modus' everything what happens is just throwed away

**Comment by PizzaProgram** [comment]
Change line 48:
    `const timerLog   = true;`

to get lot's of logs about the timer.
 (save >> NPM rebuild >> NR restart as usual.)

**Comment by PizzaProgram** [comment]
> I 'm still confused why an increase of the reading time increases the missings of push events.

At smaller interval, more reading happens. (More often.)
If the interval is 500ms ... you have to wait so long, so 1 read happens. That will report a change.
When you release the button, (let's say 100ms after last read) ... you have to wait +400ms so the device get a read again, and report back a change again.

> Isn't the mcp23017 still holding the event till it is read by the node?

Interrupt is working like this:
1. you push a button
2. Interrupt pin gets active >> sending a signal to whatever it is connected. (RPi)
3. That "main device" (RPi) starts a read >> realizing YES, 1 bit changed.
4. During the readout > MCP chip will reset the INT pin to default state.

**Comment by geoffreydemaagd** [comment]
The change is never reported (not talking about the interrupt, but just the regular read when you are not continuously reading.
So something is clearing the IO bit of the mcp23017 before the code is checking if something has been changed.

It should always report when something has happened after the read time but the code doesn't work like this.

Reading time 1000 ms, it should report something after the period if i bit changed but this is not always the case.

When you have a small read time ie100ms), less push events are missed, but a  high read time for ex 5000ms nothing is passed.

Hopefully it's clear? I'm not a native English speaking person

**Comment by PizzaProgram** [comment]
OFF:
> Hopefully it's clear? I'm not a native English speaking person

Neither me. Sometimes it is hard to exactly understand you.
I can 100% understand:
+ German language too, if that's easier for you.
+ and hungarian :-D

**Comment by PizzaProgram** [comment]
> The change is never reported

I think you misunderstand something.
NO CHANGE IS EVER GETS REPORTED !
The timer does not read a "report" from the past, but always the current, immediate state of the chip.

Only interrupt is "holding" a state of change, until you "read out" the bits.

**Comment by PizzaProgram** [comment]
> When you have a small read time ie100ms), less push events are missed, but a high read time for ex 5000ms nothing is passed.

# YES.

 ... except not "nothing". You have to press the button for min. 5 sec to get 1 "hit".

If you are using only 1 chip pro i2c bus, the default setup should be:
 - 50ms + debounce= 20ms

**OR** 

 - 20ms - no debounce
______________________

or try to fix the interrupt, so it can immediately inform you of changes.

Please measure the interrupt voltage, so we know, how it changes. 
1. Set 5000ms during test, 
2.  push the button for 5 sec long,
3. measure the voltage on the INT pin within 5 sec.
4. If you enabled detailed timer-logging, you can see on your monitor when a read happens.

**Comment by PizzaProgram** [comment]
Can you please give some feedback?

**Comment by geoffreydemaagd** [comment]
You're right the mcp23017 doesn't retain hte value but It's only available for a fraction of a period.

I changed the read cycle to the lowest possible value my RPI can handle ( +- 52 ms). Lower and the code complains that the read cycle is too fast.

Unfortunatly it's still not perfect. "Fast" clicking isn't passed  100% to NR. I have to change the code how the interrupts are emitted to NR but haven't been able to do this due to a lack of free time.

**Comment by PizzaProgram** [comment]
> the lowest possible value my RPI can handle ( +- 52 ms)

How many chips are connected to your I2C bus at the same time?

- Do you know that you can activate up to 4 I2C buses on RPi4 ?
*(I recommend to update the RPi's BIOS first, which is done automatically when updating the linux OS on it.)*
- Or you can plug in +1 USB-I2C adapter.

By separating the chips, you can have the lowest read time on each bus, like 18-20ms on a RPi4.

**Comment by geoffreydemaagd** [comment]
I stopped using the port replicators for input when the input can be a vary short period and thus those input are missed

**Comment by Joe-ab1do** [comment]
Hi @geoffreydemaagd,
I know several months have passed, but did you ever resolve this issue? Just curious as I have been working on a major update of @PizzaProgram's code, whose responses to my many questions have been very helpful over the past months. Currently testing...

Even terzijde, kijkend naar je achternaam vermoed ik dat je Nederlands bent, dus als het makkelijker is kunnen we dat ook proberen, maar het maakt deze discussie wel minder toegankelijk voor anderen.

**Comment by PizzaProgram** [comment]
I've just realized yesterday: 
## Made in 2022 a big mistake: 
 - did not upload my latest version [2.3.9.20220908] properly to here, nor to the NPM  ! :-1: 
 - the one uploaded [v2.3.8.20220907] does not work at all.

You should try this version, which is an enhanced one: 
https://flows.nodered.org/node/@joe-ab1do/mcp-pcf-aio

< OFF >
_PS: Sorry for the very late response. The last 14 month was a nightmare for me, could not work on this project._
