### ISSUE TITLE
Reading not working with pcf8574

### ISSUE THREAD

**Issue by Ghennet** [PizzaProgram/MCP23017-PCF8574-AIO#6]
Thanks for your valuable work.

Unfortunately I have problems reading with the PCF8574, it never seems to read any value, do you have any suggestions?

Tnx Simone

**Comment by PizzaProgram** [comment]
Dear Simone,

I have to admit, I've never really tried to read anything from PCF8574 chips, only use them for outputs.
So in theory it is possible, there is a bug in the code.
But it is also possible that you are using a different board based on pcf chip, and maybe an other command is needed to read the values.

Either way I need more data:
 - What configuration do you use? (need every parameter)
 - Copy the log of the PCF chip here (please delete everything else, and format it properly as text CODE )

**Comment by PizzaProgram** [comment]
I'm working on a better logging system, that you can in-/activate from the node's properties.
Currently my test system is not working for some reason I can not find, so I'm afraid to release this new version without testing.

**Comment by Joe-ab1do** [comment]
Hi Simone,
I don't know if this is still an issue for you given the many months that have passed. I have been working on a major update of @PizzaProgram's code. As such I have been testing with MCP and PCF chips including a PCF8574 using ports as both inputs and outputs.

One thing I can possibly add to the discussion is that as you may know the PCF8574 uses _quasi_ bidirectional ports (it has no internal registers including no IODIR register defining a port as either input or output). This makes the PCF very easy to use, but there is a tradeoff: a port must first be set to 1 (high), before it can be used as an input.

Let me know if this helps.

**Comment by PizzaProgram** [comment]
I've just realized yesterday: 
## Made in 2022 a big mistake: 
 - did not upload my latest version [2.3.9.20220908] properly to here, nor to the NPM  ! :-1: 
 - the one uploaded [v2.3.8.20220907] does not work at all.

You should try this version, which is an enhanced one: 
https://flows.nodered.org/node/@joe-ab1do/mcp-pcf-aio

< OFF >
_PS: Sorry for the very late response. The last 14 month was a nightmare for me, could not work on this project._
